# -*- coding: utf-8 -*-
"""HDFC Bank Stock Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xnUL3oRI25xIrf_SWS0eLZKiEOiL9Sg-
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/MRF.NS.csv')

"""### Data Preprocessing

First, we need to clean and prepare the stock data. This involves converting the date column to the correct format, setting it as the DataFrame index, and calculating daily returns.
"""

# Check if 'Unnamed: 0' column exists. If so, it implies the DataFrame hasn't been fully preprocessed for dates yet.
if 'Unnamed: 0' in df.columns:
    # Rename the first column to 'Date'
    df = df.rename(columns={'Unnamed: 0': 'Date'})
    # Convert 'Date' column to datetime objects
    df['Date'] = pd.to_datetime(df['Date'])
    # Set 'Date' as the index of the DataFrame
    df = df.set_index('Date')
# If 'Unnamed: 0' is not present, check if 'Date' is already the index and ensure its type.
elif df.index.name == 'Date' and not pd.api.types.is_datetime64_any_dtype(df.index):
    df.index = pd.to_datetime(df.index)
# If 'Date' is already the index and datetime, no action is needed here.

# Sort the DataFrame by Date
df = df.sort_index()

# Handle any potential missing values (e.g., forward fill or backward fill if appropriate for stock data)
df.fillna(method='ffill', inplace=True)

# Calculate Daily Returns
df['Daily_Return'] = df['Close'].pct_change() * 100

# Extract time-based features for filtering and analysis
df['Year'] = df.index.year
df['Month'] = df.index.month
df['Quarter'] = df.index.quarter
df['Day_of_Week'] = df.index.dayofweek # Monday=0, Sunday=6

print("DataFrame Info after preprocessing:")
df.info()

print("\nFirst 5 rows of the preprocessed DataFrame:")
display(df.head())

"""### 1. Stock Performance Overview (KPI Cards)

Here we will calculate and display key performance indicators: Current Stock Price, 52 Week High, 52 Week Low, and Market Trend (daily percentage change).
"""

# Current Stock Price (Last Closing Price)
current_price = df['Close'].iloc[-1]

# 52 Week High and Low
# Ensure we have at least 252 trading days (approx. 52 weeks * 5 days/week) of data
if len(df) >= 252:
    df_last_52_weeks = df['Close'].iloc[-252:]
    week_high_52 = df_last_52_weeks.max()
    week_low_52 = df_last_52_weeks.min()
else:
    # If less than 52 weeks of data, use available max/min
    week_high_52 = df['Close'].max()
    week_low_52 = df['Close'].min()

# Market Trend (% Change from previous day's close)
market_trend_percent = df['Daily_Return'].iloc[-1]

print(f"Current Stock Price: {current_price:.2f}")
print(f"52 Week High: {week_high_52:.2f}")
print(f"52 Week Low: {week_low_52:.2f}")
print(f"Market Trend (Last Day Change): {market_trend_percent:.2f}%")

"""### 2. Price Movement Charts

We will visualize the stock's price movement using a line chart for the closing price and a candlestick chart for Open, High, Low, and Close prices.
"""

# Line chart for Closing Price
plt.figure(figsize=(14, 7))
plt.plot(df.index, df['Close'], label='Closing Price', color='blue')
plt.title('MRF.NS Stock Price Movement (Closing Price)')
plt.xlabel('Date')
plt.ylabel('Closing Price (INR)')
plt.grid(True)
plt.legend()
plt.show()

"""#### Candlestick Chart

For a more detailed view of daily price movements (Open, High, Low, Close), we will use a candlestick chart. We might need to install the `mplfinance` library if it's not already available.
"""

# Commented out IPython magic to ensure Python compatibility.
# Install mplfinance if not already installed
try:
    import mplfinance as mpf
except ImportError:
#     %pip install mplfinance
    import mplfinance as mpf

# Prepare data for candlestick chart (mplfinance requires specific column names and index)
# Ensure column names are correctly capitalized as per the DataFrame
ohlc_df = df[['Open', 'High', 'Low', 'Close', 'Volume']]

# Plot candlestick chart for a recent period (e.g., last 6 months) to keep it readable
# You can adjust the `slice_date` to see different periods
# Use the maximum date in the DataFrame as the reference point for 'recent' data
slice_date = df.index.max() - pd.DateOffset(months=6)
recent_ohlc = ohlc_df[ohlc_df.index >= slice_date]

if not recent_ohlc.empty:
    fig, axes = mpf.plot(recent_ohlc,
                         type='candle',
                         style='yahoo',
                         volume=True,
                         title='MRF.NS Candlestick Chart (Last 6 Months)',
                         ylabel='Price (INR)',
                         ylabel_lower='Volume',
                         figscale=1.5,
                         returnfig=True)
    fig.show()
else:
    print(f"Not enough recent data to plot a candlestick chart for the last 6 months ending {df.index.max().strftime('%Y-%m-%d')}.")

"""### 3. Moving Average Analysis for 365 days

We will calculate and plot the 365-day Simple Moving Average (SMA) to analyze long-term trends in the stock price.
"""

# Calculate 365-day Simple Moving Average (SMA)
df['SMA_365'] = df['Close'].rolling(window=365).mean()

# Plotting the Closing Price and 365-day SMA
plt.figure(figsize=(14, 7))
plt.plot(df.index, df['Close'], label='Closing Price', color='blue', alpha=0.7)
plt.plot(df.index, df['SMA_365'], label='365-Day SMA', color='red', linestyle='--')
plt.title('MRF.NS Stock Price with 365-Day Moving Average')
plt.xlabel('Date')
plt.ylabel('Price (INR)')
plt.grid(True)
plt.legend()
plt.show()

"""### 4. Monthly Return Analysis in %

We will calculate the monthly percentage return and visualize it to understand the stock's performance on a monthly basis.
"""

# Calculate monthly returns
monthly_returns = df['Close'].resample('ME').ffill().pct_change() * 100
monthly_returns = monthly_returns.dropna()

plt.figure(figsize=(14, 7))
monthly_returns.plot(kind='bar', color=np.where(monthly_returns > 0, 'green', 'red'))
plt.title('MRF.NS Monthly Returns (%)')
plt.xlabel('Date')
plt.ylabel('Return (%)')
plt.grid(axis='y', linestyle='--')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""### 5. Volatility and Risk Section (Rolling Volatility Chart)

We will calculate and plot the rolling volatility (standard deviation of daily returns) to assess the stock's risk over time.
"""

import matplotlib.pyplot as plt

# Calculate 30-day Rolling Volatility (standard deviation of daily returns)
df['Volatility'] = df['Daily_Return'].rolling(window=30).std()

# Plotting the Rolling Volatility
plt.figure(figsize=(14, 7))
plt.plot(df.index, df['Volatility'], label='30-Day Rolling Volatility', color='purple')
plt.title('MRF.NS 30-Day Rolling Volatility')
plt.xlabel('Date')
plt.ylabel('Volatility (Standard Deviation of Daily Returns)')
plt.grid(True)
plt.legend()
plt.show()

"""### 6. High vs Low Price Analysis (Area Chart)

We will create an area chart to visualize the daily high and low prices, showing the trading range for the stock over time.
"""

plt.figure(figsize=(14, 7))
plt.fill_between(df.index, df['Low'], df['High'], color='skyblue', alpha=0.4, label='Price Range (High-Low)')
plt.plot(df.index, df['Close'], color='blue', alpha=0.6, label='Closing Price')
plt.title('MRF.NS High vs Low Price Analysis')
plt.xlabel('Date')
plt.ylabel('Price (INR)')
plt.grid(True)
plt.legend()
plt.show()

"""### 7. Trading Volume Insights

We will identify the highest and lowest trading volume days to understand significant activity periods.
"""

# Highest Volume Day
highest_volume_day = df.loc[df['Volume'].idxmax()]
print(f"Highest Volume Day: {highest_volume_day.name.strftime('%Y-%m-%d')} with Volume: {highest_volume_day['Volume']:.2f}")

# Lowest Volume Day
lowest_volume_day = df.loc[df['Volume'].idxmin()]
print(f"Lowest Volume Day: {lowest_volume_day.name.strftime('%Y-%m-%d')} with Volume: {lowest_volume_day['Volume']:.2f}")

# Plotting Trading Volume over time
plt.figure(figsize=(14, 7))
plt.bar(df.index, df['Volume'], color='gray', alpha=0.7)
plt.title('MRF.NS Trading Volume Over Time')
plt.xlabel('Date')
plt.ylabel('Volume')
plt.grid(True)
plt.show()

"""### 9. Stock Return Calculator

This section provides a calculator to determine the profit/loss and Return on Investment (ROI) based on a selected date range and investment amount.
"""

def calculate_returns(start_date_str, end_date_str, investment_amount):
    try:
        start_date = pd.to_datetime(start_date_str)
        end_date = pd.to_datetime(end_date_str)
    except ValueError:
        print("Error: Invalid date format. Please use YYYY-MM-DD.")
        return

    # Filter data for the specified date range
    filtered_df = df.loc[start_date:end_date]

    if filtered_df.empty:
        print(f"No data available for the selected date range: {start_date_str} to {end_date_str}.")
        return

    # Get the closing price on the start and end dates
    # Use .iloc[0] and .iloc[-1] to get the first and last available prices within the range
    buy_price = filtered_df['Close'].iloc[0]
    sell_price = filtered_df['Close'].iloc[-1]

    if buy_price == 0:
        print("Error: Buy price is zero, cannot calculate returns.")
        return

    # Calculate number of shares bought
    shares_bought = investment_amount / buy_price

    # Calculate final value of investment
    final_value = shares_bought * sell_price

    # Calculate profit/loss
    profit_loss = final_value - investment_amount

    # Calculate ROI in percentage
    roi_percent = (profit_loss / investment_amount) * 100

    print(f"Investment Start Date: {start_date.strftime('%Y-%m-%d')}")
    print(f"Investment End Date: {end_date.strftime('%Y-%m-%d')}")
    print(f"Initial Investment: INR {investment_amount:.2f}")
    print(f"Buy Price (on {filtered_df.index[0].strftime('%Y-%m-%d')}): INR {buy_price:.2f}")
    print(f"Sell Price (on {filtered_df.index[-1].strftime('%Y-%m-%d')}): INR {sell_price:.2f}")
    print(f"Shares Purchased: {shares_bought:.2f}")
    print(f"Final Value: INR {final_value:.2f}")
    print(f"Profit/Loss: INR {profit_loss:.2f}")
    print(f"ROI: {roi_percent:.2f}%")

# Example Usage:
# You can change these dates and investment amount
start_date_example = '2021-01-01' # Adjusted to be within data range
end_date_example = '2021-09-29'   # Adjusted to be within data range
investment_example = 100000 # INR 1 Lakh

print("\n--- Example Stock Return Calculation ---")
calculate_returns(start_date_example, end_date_example, investment_example)

start_date_example_2 = '2020-03-01'
end_date_example_2 = '2020-09-01'
investment_example_2 = 50000 # INR 50,000

print("\n--- Another Example Stock Return Calculation ---")
calculate_returns(start_date_example_2, end_date_example_2, investment_example_2)

"""### 10. Dashboard Filters

This section provides interactive filters to refine the data displayed in the dashboard components. You can filter by a specific date range, year, month, or quarter to analyze HDFC Bank's stock performance under various conditions.
"""

import ipywidgets as widgets
from IPython.display import display, clear_output, HTML

def create_filtered_dashboard(start_date, end_date, selected_year, selected_month, selected_quarter):
    clear_output(wait=True)
    display(widgets.HBox([date_range_picker_widget, year_selector, month_selector, quarter_selector]))

    filtered_df = df.copy()

    # Apply date range filter first
    if start_date is not None and end_date is not None:
        filtered_df = filtered_df.loc[start_date:end_date]

    # Apply year filter
    if selected_year != 'All':
        filtered_df = filtered_df[filtered_df['Year'] == selected_year]

    # Apply month filter
    if selected_month != 'All':
        filtered_df = filtered_df[filtered_df['Month'] == selected_month]

    # Apply quarter filter
    if selected_quarter != 'All':
        filtered_df = filtered_df[filtered_df['Quarter'] == selected_quarter]

    if filtered_df.empty:
        print("No data available for the selected filters.")
        return

    print("### Filtered MRF.NS Stock Dashboard ###\n")

    # --- 1. Stock Performance Overview (KPI Cards) ---
    print("**1. Stock Performance Overview (KPI Cards)**")
    current_price_filtered = filtered_df['Close'].iloc[-1]

    # Calculate 52-week high/low within the filtered data. Adjust window if filtered data is less than 252 days.
    if len(filtered_df) >= 252:
        df_last_52_weeks_filtered = filtered_df['Close'].iloc[-252:]
        week_high_52_filtered = df_last_52_weeks_filtered.max()
        week_low_52_filtered = df_last_52_weeks_filtered.min()
    else:
        week_high_52_filtered = filtered_df['Close'].max()
        week_low_52_filtered = filtered_df['Close'].min()

    market_trend_percent_filtered = filtered_df['Daily_Return'].iloc[-1] if not filtered_df['Daily_Return'].isnull().all() else 0.0

    # Create HTML for KPI cards
    kpi_html = f"""
    <div style='display: flex; justify-content: space-around; flex-wrap: wrap; margin-bottom: 20px;'>
        <div style='background-color: #f0f8ff; border: 1px solid #add8e6; border-radius: 8px; padding: 15px; margin: 10px; text-align: center; width: 200px;'>
            <h4>Current Price</h4>
            <p style='font-size: 1.5em; font-weight: bold;'>₹{current_price_filtered:.2f}</p>
        </div>
        <div style='background-color: #f0fff0; border: 1px solid #90ee90; border-radius: 8px; padding: 15px; margin: 10px; text-align: center; width: 200px;'>
            <h4>High (Filtered Period)</h4>
            <p style='font-size: 1.5em; font-weight: bold;'>₹{week_high_52_filtered:.2f}</p>
        </div>
        <div style='background-color: #fff0f5; border: 1px solid #ffb6c1; border-radius: 8px; padding: 15px; margin: 10px; text-align: center; width: 200px;'>
            <h4>Low (Filtered Period)</h4>
            <p style='font-size: 1.5em; font-weight: bold;'>₹{week_low_52_filtered:.2f}</p>
        </div>
        <div style='background-color: #fffacd; border: 1px solid #ffd700; border-radius: 8px; padding: 15px; margin: 10px; text-align: center; width: 200px;'>
            <h4>Market Trend (Last Day)</h4>
            <p style='font-size: 1.5em; font-weight: bold; color: {'green' if market_trend_percent_filtered >= 0 else 'red'};'>{market_trend_percent_filtered:.2f}%</p>
        </div>
    </div>
    """
    display(HTML(kpi_html))

    # --- 2. Price Movement Charts (Line Chart) & 3. Moving Average Analysis for 365 days ---
    print("**2 & 3. Price Movement (Line Chart for Closing Price) and Moving Average Analysis**")
    fig, axes = plt.subplots(1, 2, figsize=(20, 6)) # Create two subplots side-by-side

    # Plot 1: Closing Price Line Chart
    axes[0].plot(filtered_df.index, filtered_df['Close'], label='Closing Price', color='blue')
    axes[0].set_title('MRF.NS Stock Price Movement (Filtered)')
    axes[0].set_xlabel('Date')
    axes[0].set_ylabel('Closing Price (INR)')
    axes[0].grid(True)
    axes[0].legend()

    # Plot 2: Moving Average Analysis
    if len(filtered_df) >= 365:
        filtered_df['SMA_365'] = filtered_df['Close'].rolling(window=365).mean()
        axes[1].plot(filtered_df.index, filtered_df['Close'], label='Closing Price', color='blue', alpha=0.7)
        axes[1].plot(filtered_df.index, filtered_df['SMA_365'], label='365-Day SMA', color='red', linestyle='--')
        axes[1].set_title('MRF.NS Stock Price with 365-Day Moving Average (Filtered)')
        axes[1].set_xlabel('Date')
        axes[1].set_ylabel('Price (INR)')
        axes[1].grid(True)
        axes[1].legend()
    else:
        axes[1].text(0.5, 0.5, 'Not enough data for 365-day SMA', horizontalalignment='center', verticalalignment='center', transform=axes[1].transAxes, fontsize=12)
        axes[1].set_title('365-Day Moving Average (Filtered)')
        axes[1].set_xlabel('Date')
        axes[1].set_ylabel('Price (INR)')
        axes[1].grid(True)

    plt.tight_layout()
    plt.show()

    # Candlestick chart requires mplfinance and specific data structure,
    # and can be too dense for interactive filtering if not carefully managed.
    # Keeping it separate or adding as an optional plot is better for dynamic dashboards.
    # For this consolidated view, we'll focus on the line chart for simplicity.

    # --- 4. Monthly Return Analysis in % & 5. Volatility and Risk Section (Rolling Volatility Chart) ---
    print("\n**4 & 5. Monthly Return Analysis (%) and Volatility and Risk (Rolling Volatility Chart)**")
    fig, axes = plt.subplots(1, 2, figsize=(20, 6))

    # Plot 1: Monthly Return Analysis
    monthly_returns_filtered = filtered_df['Close'].resample('ME').ffill().pct_change() * 100
    monthly_returns_filtered = monthly_returns_filtered.dropna()

    if not monthly_returns_filtered.empty:
        monthly_returns_filtered.plot(kind='bar', color=np.where(monthly_returns_filtered > 0, 'green', 'red'), ax=axes[0])
        axes[0].set_title('MRF.NS Monthly Returns (%) (Filtered)')
        axes[0].set_xlabel('Date')
        axes[0].set_ylabel('Return (%)')
        axes[0].grid(axis='y', linestyle='--')
        axes[0].tick_params(axis='x', rotation=45)
    else:
        axes[0].text(0.5, 0.5, 'No monthly returns data available for the filtered period.', horizontalalignment='center', verticalalignment='center', transform=axes[0].transAxes, fontsize=12)
        axes[0].set_title('MRF.NS Monthly Returns (%) (Filtered)')
        axes[0].set_xlabel('Date')
        axes[0].set_ylabel('Return (%)')
        axes[0].grid(axis='y', linestyle='--')

    # Plot 2: Volatility and Risk Section
    if len(filtered_df) >= 30:
        filtered_df['Volatility'] = filtered_df['Daily_Return'].rolling(window=30).std()
        axes[1].plot(filtered_df.index, filtered_df['Volatility'], label='30-Day Rolling Volatility', color='purple')
        axes[1].set_title('MRF.NS 30-Day Rolling Volatility (Filtered)')
        axes[1].set_xlabel('Date')
        axes[1].set_ylabel('Volatility (Standard Deviation of Daily Returns)')
        axes[1].grid(True)
        axes[1].legend()
    else:
        axes[1].text(0.5, 0.5, 'Not enough data in the filtered period to calculate 30-day Rolling Volatility.', horizontalalignment='center', verticalalignment='center', transform=axes[1].transAxes, fontsize=12)
        axes[1].set_title('MRF.NS 30-Day Rolling Volatility (Filtered)')
        axes[1].set_xlabel('Date')
        axes[1].set_ylabel('Volatility (Standard Deviation of Daily Returns)')
        axes[1].grid(True)

    plt.tight_layout()
    plt.show()

    # --- 6. High vs Low Price Analysis (Area Chart) & 7. Trading Volume Insights ---
    print("\n**6 & 7. High vs Low Price Analysis (Area Chart) and Trading Volume Insights**")
    fig, axes = plt.subplots(1, 2, figsize=(20, 6))

    # Plot 1: High vs Low Price Analysis
    axes[0].fill_between(filtered_df.index, filtered_df['Low'], filtered_df['High'], color='skyblue', alpha=0.4, label='Price Range (High-Low)')
    axes[0].plot(filtered_df.index, filtered_df['Close'], color='blue', alpha=0.6, label='Closing Price')
    axes[0].set_title('MRF.NS High vs Low Price Analysis (Filtered)')
    axes[0].set_xlabel('Date')
    axes[0].set_ylabel('Price (INR)')
    axes[0].grid(True)
    axes[0].legend()

    # Plot 2: Trading Volume Insights
    if not filtered_df.empty and 'Volume' in filtered_df.columns:
        highest_volume_day_filtered = filtered_df.loc[filtered_df['Volume'].idxmax()]
        lowest_volume_day_filtered = filtered_df.loc[filtered_df['Volume'].idxmin()]
        print(f"Highest Volume Day in Filtered Period: {highest_volume_day_filtered.name.strftime('%Y-%m-%d')} with Volume: {highest_volume_day_filtered['Volume']:.2f}")
        print(f"Lowest Volume Day in Filtered Period: {lowest_volume_day_filtered.name.strftime('%Y-%m-%d')} with Volume: {lowest_volume_day_filtered['Volume']:.2f}")
        axes[1].bar(filtered_df.index, filtered_df['Volume'], color='gray', alpha=0.7)
        axes[1].set_title('MRF.NS Trading Volume Over Time (Filtered)')
        axes[1].set_xlabel('Date')
        axes[1].set_ylabel('Volume')
        axes[1].grid(True)
    else:
        axes[1].text(0.5, 0.5, 'No volume data available for the filtered period.', horizontalalignment='center', verticalalignment='center', transform=axes[1].transAxes, fontsize=12)
        axes[1].set_title('MRF.NS Trading Volume Over Time (Filtered)')
        axes[1].set_xlabel('Date')
        axes[1].set_ylabel('Volume')
        axes[1].grid(True)

    plt.tight_layout()
    plt.show()


# Get unique years, months, and quarters for dropdowns
years = ['All'] + sorted(df['Year'].unique().tolist())
months = ['All'] + sorted(df['Month'].unique().tolist())
quarters = ['All'] + sorted(df['Quarter'].unique().tolist())

# Create widgets
date_range_picker_start = widgets.DatePicker(description='Start Date')
date_range_picker_start.value = df.index.min().date()
date_range_picker_end = widgets.DatePicker(description='End Date')
date_range_picker_end.value = df.index.max().date()

year_selector = widgets.Dropdown(options=years, value='All', description='Year:')
month_selector = widgets.Dropdown(options=months, value='All', description='Month:')
quarter_selector = widgets.Dropdown(options=quarters, value='All', description='Quarter:')

# Combine date pickers into a single HBox for display
date_range_picker_widget = widgets.HBox([widgets.Label('Date Range:'), date_range_picker_start, date_range_picker_end])

# Use interactive_output to link widgets to the function
interactive_output = widgets.interactive_output(create_filtered_dashboard,
                                                {'start_date': date_range_picker_start,
                                                 'end_date': date_range_picker_end,
                                                 'selected_year': year_selector,
                                                 'selected_month': month_selector,
                                                 'selected_quarter': quarter_selector})

# Display widgets and output
display(widgets.VBox([date_range_picker_widget, widgets.HBox([year_selector, month_selector, quarter_selector]), interactive_output]))